/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { codeReferencesGetStatistics } from "../funcs/codeReferencesGetStatistics.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CodeReferences extends ClientSDK {
  /**
   * Get code references statistics for flags
   *
   * @remarks
   * Get statistics about all the code references across repositories for all flags in your project that have code references in the default branch, for example, `main`. Optionally, you can include the `flagKey` query parameter to limit your request to statistics about code references for a single flag. This endpoint returns the number of references to your flag keys in your repositories, as well as a link to each repository.
   */
  async getStatistics(
    request: operations.GetStatisticsRequest,
    options?: RequestOptions,
  ): Promise<components.StatisticCollectionRep> {
    return unwrapAsync(codeReferencesGetStatistics(
      this,
      request,
      options,
    ));
  }
}
