/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @launchdarkly/mcp-server SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx codeReferencesGetStatistics.example.ts
 */

import { LaunchDarkly } from "@launchdarkly/mcp-server";

const launchDarkly = new LaunchDarkly({
  apiKey: process.env["LAUNCHDARKLY_API_KEY"] ?? "",
});

async function main() {
  const result = await launchDarkly.codeReferences.getStatistics({
    projectKey: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
