/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStatisticsRequest = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * Filter results to a specific flag key
   */
  flagKey?: string | undefined;
};

/** @internal */
export const GetStatisticsRequest$inboundSchema: z.ZodType<
  GetStatisticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectKey: z.string(),
  flagKey: z.string().optional(),
});
/** @internal */
export type GetStatisticsRequest$Outbound = {
  projectKey: string;
  flagKey?: string | undefined;
};

/** @internal */
export const GetStatisticsRequest$outboundSchema: z.ZodType<
  GetStatisticsRequest$Outbound,
  z.ZodTypeDef,
  GetStatisticsRequest
> = z.object({
  projectKey: z.string(),
  flagKey: z.string().optional(),
});

export function getStatisticsRequestToJSON(
  getStatisticsRequest: GetStatisticsRequest,
): string {
  return JSON.stringify(
    GetStatisticsRequest$outboundSchema.parse(getStatisticsRequest),
  );
}
export function getStatisticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetStatisticsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStatisticsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStatisticsRequest' from JSON`,
  );
}
